### ISSUE TITLE
`socket.timeout` on client side `eval_agent.py` when specifying a time to wait before adding random players

### ISSUE THREAD

**Issue by EmileDeBruyn** [HelmholtzAI-FZJ/hearts-gym#3]
# Issue description
Specifying a `--wait_duration_sec` value leads to `socket.timeout`s on the client side. Currently, there is no other way (afaik) to start a game with random players to evaluate the performance of the baseline default PPO algorithm.

## `start_server.py` command and log

```bash
$ python start_server.py --num_parallel_games 1 --wait_duration_sec 15

WARNING:tensorflow:From /p/project/cslbio/debruyn/miniconda3/envs/hearts-gym/lib/python3.8/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:hearts_gym.server.hearts_server:Warning: set `num_procs = 1`; cannot have more processes than games.
Server started on ('127.0.0.1', 65535).
Registered ('127.0.0.1', 60612) at index 0.
Waiting...
```

## `eval_agent.py` command and log

```bash
$ python start_server.py --num_parallel_games 1 --wait_duration_sec 15
$ python eval_agent.py --server_address 127.0.0.1 --port 65535 --name 'default_algo' --algorithm PPO ../external_results/PPO/PPO_Hearts-v0_d7ff9_00000_0_2021-07-20_10-47-14/checkpoint_000500/checkpoint-500 
WARNING:tensorflow:From /p/project/cslbio/debruyn/miniconda3/envs/hearts-gym/lib/python3.8/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
2021-07-21 11:10:00,390 INFO services.py:1267 -- View the Ray dashboard at http://127.0.0.1:8265
Connected to server.
Server says: default_algo connected to server; 1/4 players connected...
Positioned at index 0.
2021-07-21 11:10:25,050 INFO trainer.py:669 -- Tip: set framework=tfe or the --eager flag to enable TensorFlow eager execution
2021-07-21 11:10:25,050 INFO trainer.py:694 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
2021-07-21 11:10:25,902 WARNING util.py:53 -- Install gputil for GPU system monitoring.
2021-07-21 11:10:25,951 INFO trainable.py:377 -- Restored on 134.94.0.105 from checkpoint: ../external_results/PPO/PPO_Hearts-v0_d7ff9_00000_0_2021-07-20_10-47-14/checkpoint_000500/checkpoint-500
2021-07-21 11:10:25,951 INFO trainable.py:385 -- Current state after restoring: {'_iteration': 500, '_timesteps_total': None, '_time_total': 4112.153238773346, '_episodes_total': 39215}
Server says: Waiting for more players...
Unable to receive data from server.
Traceback (most recent call last):
  File "eval_agent.py", line 498, in <module>
    main()
  File "eval_agent.py", line 428, in main
    data = wait_for_data(
  File "eval_agent.py", line 289, in wait_for_data
    data = receive_data(client, max_receive_bytes, max_total_receive_bytes)
  File "eval_agent.py", line 240, in receive_data
    msg_length, data_shard = _receive_msg_length(client, max_receive_bytes)
  File "eval_agent.py", line 196, in _receive_msg_length
    data_shard = _receive_data_shard(client, max_receive_bytes)
  File "eval_agent.py", line 163, in _receive_data_shard
    data = client.recv(max_receive_bytes)
socket.timeout: timed out
```

**Comment by janEbert** [comment]
Thanks for the detailed description and logs. :)

**Comment by EmileDeBruyn** [comment]
Thanks for getting to it so quickly. I'll try the fix out on my side during the evening.
